// Version 3.0 - Updated Course Content & Instructor
import { Course, Instructor } from './types';

export const instructors: Instructor[] = [
  {
    id: 'instructor-1',
    name: 'The Architect',
    avatarId: 'instructor-avatar-1',
    bio: 'An operator who has successfully navigated the grey zones of global finance and sovereignty for over two decades. A master of systems, structures, and the art of invisibility.',
  },
  {
    id: 'instructor-2',
    name: 'The Cypherpunk',
    avatarId: 'instructor-avatar-2',
    bio: 'A leading voice in the cryptocurrency space, specializing in privacy, self-custody, and the construction of parallel financial systems.',
  },
];

const placeholderThumbnail = "https://images.unsplash.com/photo-1639322537228-f710d846310a?q=80&w=2532&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"; // Abstract dark crypto/security image

export const courses: Course[] = [
  // Course 1
  {
    id: 'guy-fawkes-1',
    name: 'THE SOVEREIGN SELF (Ghost Anonymity)',
    shortDescription: 'Become a ghost. Erase your digital soulprint and create untraceable identities.',
    longDescription: "They're watching you. Right now. Your phone, your browser, your bank account—they've turned you into a digital puppet on strings. This isn't paranoia. It's your life. But what if you could cut every string? What if you could vanish from their screens while still living fully in the real world? This course isn't about hiding. It's about becoming invisible on command. You'll learn to erase your digital soulprint, create untraceable identities that work FOR you, and move through systems like a ghost—seen only when YOU choose to be seen. Your freedom starts with deletion.",
    price: 62,
    vendettaMachineUrl: 'https://vendetta-machine.vercel.app/art/guy-fawkes-1',
    imageId: 'course-sovereign-self',
    teaserVideoUrl: 'https://youtu.be/pzfDord_yOI',
    category: 'Security',
    duration: '4 hours',
    level: 'Advanced',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 120,
    thumbnailUrl: placeholderThumbnail,
    introductionScript: "Hello. Welcome. Before we talk about money, or entities, or anything else, we need to talk about you. Or rather, the 'you' the world thinks it knows. You have a digital footprint, a legal name, a data trail that defines and confines you. But what if that was a choice, not a fact? In this course, I'm not going to teach you how to hide. I'm going to show you how to be everywhere and nowhere at once. We will deconstruct the idea of a single self and rebuild it as a powerful, multi-faceted tool. You will learn to create personas, control your data, and navigate the systems of verification not as a subject, but as a master. This is the first and most important step. Let's begin.",
    modules: [
      {
        id: 'm1',
        title: 'Video Curriculum',
        lessons: [
          { id: 'l1.1', title: 'Your Name is a Target: Why You\'re Being Hunted Right Now', duration: 25, youtubeVideoId: 'Z_15Zv8js9I', content: 'The brutal truth about how your single identity makes you a sitting duck for data brokers, debt collectors, and government overreach—and why having one name is the ultimate vulnerability in 2025.', isPreview: true },
          { id: 'l1.2', title: 'Create Your First Fake Identity (Yes, It\'s Legal)', duration: 35, youtubeVideoId: 'Lu9mpBV0YjY', content: 'Step-by-step walkthrough of building your first operational alias—from generating a believable backstory to creating digital footprints that pass even deep background checks. No shady tactics, just smart legal loopholes.', isPreview: false },
          { id: 'l1.3', title: 'Delete Your Digital Shadow: The 5-Minute Purge', duration: 30, youtubeVideoId: 'astqlEQVW68', content: 'The exact tools and scripts to mass-delete your personal data from 90% of data broker sites in under 5 minutes. Watch your digital shadow shrink in real-time as you regain control.', isPreview: false },
          { id: 'l1.4', title: 'Trick KYC Systems: Give Them Fake Clues That Work', duration: 28, youtubeVideoId: '-Ftq8Xyuocw', content: 'How to satisfy bank and exchange verification requirements by strategically leaking false information that satisfies their algorithms while protecting your real identity. The art of controlled digital deception.', isPreview: false },
          { id: 'l1.5', title: 'Run 3 Identities Like a Spy: Your Digital Army', duration: 40, youtubeVideoId: 'rjyy0l2Z0Os', content: 'Advanced compartmentalization tactics for managing multiple personas simultaneously—each with its own email, phone number, and digital history—without cross-contamination or burnout.', isPreview: false },
        ],
      },
    ],
  },
  // Course 2
  {
    id: 'guy-fawkes-2',
    name: 'ESCAPE THE TAX TRAP',
    shortDescription: 'Legally owe $0 to any government on earth.',
    longDescription: 'You work 5 months every year just to pay them. Your sweat, your dreams, your family\'s future—they take it all with a smile and call it "civic duty." But what if you could keep every dollar you earn? Not through loopholes they\'ll close tomorrow, but through ancient legal frameworks they can\'t touch. This course is your tax rebellion manual. You\'ll learn to legally plant flags in countries that don\'t care about your birth certificate, exploit territorial tax systems that ignore foreign income, and become a "nowhere man" that no government can claim. Your money belongs to you—not them. It\'s time to take it back.',
    price: 62,
    vendettaMachineUrl: 'https://vendetta-machine.vercel.app/art/guy-fawkes-2',
    imageId: 'course-tax-trap',
    teaserVideoUrl: 'https://youtu.be/94F9R8YtVu8',
    category: 'Global Strategy',
    duration: '5 hours',
    level: 'Expert',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 97,
    thumbnailUrl: placeholderThumbnail,
    introductionScript: "You were taught that the map of the world is fixed. That the country you were born in holds permanent power over your wealth and your freedom. I am here to tell you that this is a lie, a story told to keep you in place. In this course, we are going to redraw that map. I will show you how to turn borders into opportunities and passports into keys. You will learn the strategies to acquire new residencies and citizenships, how to structure your life to legally owe nothing to the countries that seek to tax you most, and how to become a 'Nowhere Man'—present where you need to be, but legally anchored nowhere. Your geography is no longer your destiny. It's your greatest weapon.",
    modules: [
      {
        id: 'm1',
        title: 'Video Curriculum',
        lessons: [
          { id: 'l2.1', title: 'Your Birthplace is a Prison: Break Free NOW', duration: 30, youtubeVideoId: '5HoDzfZgxjQ', content: 'How your country of birth is the single biggest financial liability you have—and the exact legal pathways to sever its claim on your wealth without ever setting foot in another country.', isPreview: true },
          { id: 'l2.2', title: 'Buy Your Second Passport (Before They Close the Door)', duration: 45, youtubeVideoId: 'rXbAqAzAdjA', content: 'The last remaining citizenship-by-investment programs that still work in 2025, with exact ROI calculations showing how much you\'ll save versus the $100k-$2M investment required.', isPreview: false },
          { id: 'l2.3', title: 'Live Anywhere, Pay Taxes Nowhere: The Digital Nomad Lie EXPOSED', duration: 40, youtubeVideoId: 'k0TfNd4LJnE', content: 'Why "digital nomad visas" are tax traps for the naive—and the real strategy of using temporary residency to establish permanent tax freedom while maintaining your lifestyle.', isPreview: false },
          { id: 'l2.4', title: 'The \'Nowhere Man\' Trick: How to Disappear From Tax Records', duration: 35, youtubeVideoId: '0dBIDK9fhPY', content: 'Advanced jurisdictional layering techniques that make you legally stateless for tax purposes while maintaining full banking access and travel freedom—no physical relocation required.', isPreview: false },
          { id: 'l2.5', title: 'Your Government Hates You: Play Countries Against Each Other', duration: 50, youtubeVideoId: 'tDnw2_0LYJQ', content: 'How to create legal conflict between tax authorities so they waste years fighting each other while your money grows untouched in neutral jurisdictions.', isPreview: false },
        ],
      },
    ],
  },
  // Course 3
  {
    id: 'guy-fawkes-3',
    name: "UNTOUCHABLE WEALTH",
    shortDescription: 'Own nothing, control everything. Hide $10M+ from lawyers and governments.',
    longDescription: "One lawsuit. One bitter ex-spouse. One corrupt politician with a grudge. That's all it takes to lose everything you've built. Your assets are naked. Exposed. Waiting for the wolves to feast. This course is your armor forge. You'll learn the exact legal structures billionaires use to make their wealth disappear from court records—structures so powerful that judges simply give up. Wyoming LLCs that laugh at lawsuits. Offshore trusts that can't be pierced. Corporate veils so thick that creditors walk away in frustration. This isn't about greed. It's about survival. Your life's work deserves to outlive you—not be devoured by predators the moment you're vulnerable.",
    price: 62,
    vendettaMachineUrl: 'https://vendetta-machine.vercel.app/art/guy-fawkes-3',
    imageId: 'course-untouchable-wealth',
    teaserVideoUrl: 'https://youtu.be/1v5SKypfclY',
    category: 'Asset Protection',
    duration: '6 hours',
    level: 'Expert',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 119,
    thumbnailUrl: placeholderThumbnail,
    introductionScript: "Look at any great fortune, and you will not find a person. You will find a structure. A web of companies, a fortress of trusts. The wealthy learned long ago that ownership is a liability. Control is what matters. In this course, I will hand you the same tools. You'll learn to think not like an investor, but like an architect. We'll build your financial fortress brick by brick, from the Wyoming LLC that forms the foundation to the Cook Islands Trust that serves as the impregnable keep. I'll show you how to layer these entities, how to manage them remotely, and how to use them to create a perfect separation between you and your wealth. This is where your assets become truly untouchable.",
    modules: [
      {
        id: 'm1',
        title: 'Video Curriculum',
        lessons: [
          { id: 'l3.1', title: 'Own Nothing, Control Everything: The Billionaire Secret', duration: 35, youtubeVideoId: 'zRyv3w71QdM', content: 'The psychological shift from "ownership" to "control"—and how the world\'s wealthiest families legally separate themselves from their assets while maintaining absolute command.', isPreview: true },
          { id: 'l3.2', title: 'Wyoming LLCs: Your First Legal Force Field', duration: 45, youtubeVideoId: 'CSQUawo1jPs', content: 'Why Wyoming is the ultimate domestic asset protection haven—and the exact setup to create an LLC that laughs at lawsuits while maintaining full operational control from your living room.', isPreview: false },
          { id: 'l3.3', title: 'The Trust That Can\'t Be Broken (Even by Your Worst Enemy)', duration: 50, youtubeVideoId: 'mmoX6JJ7Cuc', content: 'How to structure an offshore asset protection trust with "Trust Protector" powers that let you fire trustees, veto distributions, and maintain de facto control while legally owning nothing.', isPreview: false },
          { id: 'l3.4', title: 'Stack Legal Shields: Make Lawsuits Give Up in 3 Days', duration: 40, youtubeVideoId: 'kUVvhE0a5yM', content: 'The multi-layered entity strategy that forces creditors to sue through 3-4 legal entities across different jurisdictions—making the cost of pursuit exceed any potential recovery.', isPreview: false },
          { id: 'l3.5', title: 'Pull the Strings From Shadows: Control Without Your Name', duration: 30, youtubeVideoId: 'Z9oIPP-hOKg', content: 'Advanced techniques for managing your entire empire through nominees, corporate directors, and private agreements—keeping your name completely absent from public records while retaining 100% control.', isPreview: false },
        ],
      },
    ],
  },
  // Course 4
  {
    id: 'guy-fawkes-4',
    name: 'THE SHADOW ECONOMY (Crypto/Banking)',
    shortDescription: 'Build your own financial system. No permission needed.',
    longDescription: "Your bank can freeze your life savings in 60 seconds. Your government can erase your purchasing power overnight. Your payment apps can ban you for having the wrong opinion. This isn't freedom. It's financial slavery with better marketing. This course is your declaration of independence. You'll learn to build your own private banking system using cryptocurrency—not as speculation, but as infrastructure. Move millions across borders while they sleep. Convert digital wealth to physical cash without begging for permission. Create payment rails that can't be censored, frozen, or traced back to you. The old system is dying. Your new financial reality starts now.",
    price: 62,
    vendettaMachineUrl: 'https://vendetta-machine.vercel.app/art/guy-fawkes-4',
    imageId: 'course-shadow-economy',
    teaserVideoUrl: 'https://youtu.be/hILVEoEm_mE',
    category: 'Crypto',
    duration: '5 hours',
    level: 'Intermediate',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 114,
    thumbnailUrl: placeholderThumbnail,
    introductionScript: "You've heard about crypto. You've seen the hype, the speculation. Now, I want you to forget all of it. In this course, we're going to explore what cryptocurrency *really* is: an entirely new set of financial rails for the world. Rails that you can own. I'm going to teach you how to use this technology not as a gambler, but as a sovereign individual. You'll learn to build a private, stable financial base using stablecoins, transact anonymously using decentralized exchanges, and most importantly, how to create your own on-ramps and off-ramps to the real world, all without asking for permission. This is your personal central bank. Let's open the doors.",
    modules: [
      {
        id: 'm1',
        title: 'Video Curriculum',
        lessons: [
          { id: 'l4.1', title: 'Banks Are Spying On You: Here\'s Your Escape Plan', duration: 30, youtubeVideoId: 'mxbABgXM4is', content: 'The shocking truth about how banks monitor your spending habits, report "suspicious activity," and freeze accounts—and the exact timeline for migrating your entire financial life off their radar.', isPreview: true },
          { id: 'l4.2', title: 'Your Crypto is at Risk: The $0 Security Setup That Works', duration: 40, youtubeVideoId: 'RTl4sS_E1bQ', content: 'How to secure millions in cryptocurrency using free, open-source tools that make exchanges and hardware wallets look like child\'s play—with step-by-step setup guides.', isPreview: false },
          { id: 'l4.3', title: 'Create Your Private USD: Stablecoins That Can\'t Be Frozen', duration: 35, youtubeVideoId: 'Gmg3VRg15mE', content: 'Why USDT and USDC are dangerous—and how to use decentralized, over-collateralized stablecoins that maintain dollar value while being completely censorship-resistant.', isPreview: false },
          { id: 'l4.4', title: 'Move $1M Without a Trace: The Invisible Transfer Method', duration: 45, youtubeVideoId: 'SxKF7HCcroY', content: 'The multi-hop DEX routing strategy that breaks chain analysis and makes large transfers completely untraceable—tested against Chainalysis and Elliptic tools.', isPreview: false },
          { id: 'l4.5', title: 'Cash Out $100k Daily: Dark Web Methods (Made Legal)', duration: 50, youtubeVideoId: 'VppVZgdutPE', content: 'How to convert cryptocurrency to physical cash through legitimate peer-to-peer networks, local merchants, and cash-intensive businesses without triggering KYC red flags.', isPreview: false },
        ],
      },
    ],
  },
  // Course 5
  {
    id: 'guy-fawkes-5',
    name: 'THE INVISIBLE ARMOR (Tax Nullification)',
    shortDescription: 'Taxation is theft. Pay $0 legally and make governments beg for mercy.',
    longDescription: "They see you as a walking ATM. The IRS wants your blood. Lawyers smell your assets like sharks smell blood. Your ex-spouse is sharpening knives for your retirement fund. This isn't paranoia—it's Tuesday. But what if you could turn the tables? What if your wealth became a weapon that makes predators back down? This course is your financial warfare manual. You'll learn the exact legal maneuvers that force tax authorities to close cases in 72 hours. The entity structures that make lawyers advise their clients to \"just walk away.\" The profit-shifting tactics that turn your $1M income into $0 taxable income legally. This isn't about compliance. It's about domination. Your money should protect you—not make you a target.",
    price: 62,
    vendettaMachineUrl: 'https://vendetta-machine.vercel.app/art/guy-fawkes-5',
    imageId: 'course-invisible-armor',
    teaserVideoUrl: 'https://youtu.be/ZcJyRInHv1o',
    category: 'Tax Strategy',
    duration: '7 hours',
    level: 'Expert',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 132,
    thumbnailUrl: placeholderThumbnail,
    introductionScript: "You have been taught to work hard, earn money, and then hand over a significant portion of it to a government that sees you as a resource. I'm here to offer you a different path. A path where tax is a choice, not a command. In this course, we move into the art of the active defense. I'll show you how corporate structures aren't just for protection, but for legally steering your profits to where they are treated best. We'll explore the world of territorial tax and non-domicile residency—the keys to unlocking a zero-tax life. This isn't evasion. This is superior design. You will learn to build a system so efficient and so robust that it simply becomes invisible to those who would seek to claim a piece of it.",
    modules: [
      {
        id: 'm1',
        title: 'Video Curriculum',
        lessons: [
          { id: 'l5.1', title: 'Tax Evasion vs Tax Avoidance: The Gray Zone That Saves Millions', duration: 30, youtubeVideoId: 'QS23vRQ0Ab0', content: 'The exact legal line between what\'s prosecutable and what\'s perfectly legal—with real case studies of people who saved $2M+ by operating in the gray zone without crossing into criminal territory.', isPreview: true },
          { id: 'l5.2', title: 'Live in Paradise, Pay $0 Tax: The Territorial Tax Hack', duration: 45, youtubeVideoId: '9SzTuOrs6Xo', content: 'How to exploit territorial tax systems in Dubai, Puerto Rico, and Georgia to earn unlimited global income while legally paying zero taxes—and the exact residency requirements to make it stick.', isPreview: false },
          { id: 'l5.3', title: 'Shift $1M in Profits Overnight: The Corporate Shell Game', duration: 50, youtubeVideoId: '8sYVX-u90_U', content: 'The multi-entity profit shifting strategy used by Fortune 500 companies—adapted for individual entrepreneurs to legally move income to zero-tax jurisdictions while maintaining full operational control.', isPreview: false },
          { id: 'l5.4', title: 'Title Your Assets to Be \'Legally Invisible\' to Creditors', duration: 40, youtubeVideoId: 'lEe6ofBvC9w', content: 'Advanced asset titling protocols that make your real estate, vehicles, and investments completely disappear from public records and creditor searches while maintaining your use and control.', isPreview: false },
          { id: 'l5.5', title: 'When IRS Knocks: The 3-Word Response That Shuts Them Down', duration: 35, youtubeVideoId: 'PWaMBXAdQEU', content: 'The exact legal language and procedural tactics to delay, derail, and defeat tax audits—including template letters that force agents to close cases due to procedural violations.', isPreview: false },
        ],
      },
    ],
  },
  // Course 6
  {
    id: 'guy-fawkes-6',
    name: 'THE IMMORTAL GAME (Legacy/Wills)',
    shortDescription: 'Lock your fortune away from greedy kids, exes & governments forever.',
    longDescription: "Your last will and testament is a suicide note. The moment you die, your life's work becomes a free-for-all. Greedy relatives you haven't seen in 20 years will crawl out of the woodwork. Your ex-spouse will claim half your estate. The government will take 40% before your kids see a dime. And your lazy nephew? He'll blow it all on Lamborghinis while your grandchildren starve. This course is your dynasty armor. You'll learn to build self-perpetuating legal structures that outlive you by centuries. Trusts that can't be broken. Digital inheritance protocols that survive nuclear war. Multi-generational wealth systems that protect your bloodline from themselves and every predator on earth. This isn't estate planning. It's legacy warfare. Your family's future depends on what you build today.",
    price: 62,
    vendettaMachineUrl: 'https://vendetta-machine.vercel.app/art/guy-fawkes-6',
    imageId: 'course-immortal-game',
    teaserVideoUrl: 'https://youtu.be/EcYiPpQPwM4',
    category: 'Legacy Planning',
    duration: '6 hours',
    level: 'Advanced',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 142,
    thumbnailUrl: placeholderThumbnail,
    introductionScript: "Everything you've built, everything you've learned—it can all be undone by one poorly written document: a will. The system is designed to take its cut the moment you're gone. But what if you could opt out? In this final course, we will build your masterpiece. Not a plan for your death, but an engine for your legacy. I will show you how to use perpetual trusts to create a structure that can last for centuries, guiding and providing for your family long after you're gone. We'll design protocols for the seamless transfer of of all your assets, both physical and digital, completely outside of any government's view. This is the final move on the chessboard. This is how you win the game, forever.",
    modules: [
      {
        id: 'm1',
        title: 'Video Curriculum',
        lessons: [
          { id: 'l6.1', title: 'Your Will is a Suicide Note: Why Your Family Will Lose Everything', duration: 30, youtubeVideoId: 'fmN92puUIaM', content: 'The brutal truth about probate court—and how 78% of estates lose over 40% of their value to taxes, lawyers, and family fighting within 18 months of death.', isPreview: true },
          { id: 'l6.2', title: 'Build a Dynasty Trust: Your Wealth That Outlives You by 200 Years', duration: 45, youtubeVideoId: 'RN6LcKiHiE0', content: 'How to structure a perpetual trust that legally bypasses estate taxes, survives multiple generations, and maintains absolute control over how and when beneficiaries receive funds.', isPreview: false },
          { id: 'l6.3', title: 'Your Crypto Will Die With You: The Digital Inheritance Time Bomb', duration: 40, youtubeVideoId: '10ms1p-f-ws', content: 'The exact protocols to ensure your Bitcoin, Ethereum, and digital assets survive your death—including multi-sig inheritance setups and dead man\'s switches that activate automatically.', isPreview: false },
          { id: 'l6.4', title: 'Protect Stupid Kids: Give Them Money Without Letting Them Ruin It', duration: 35, youtubeVideoId: 'v9vqg54VjS0', content: 'Advanced trust provisions that provide heirs with comfortable lifestyles while restricting access to principal until they prove financial maturity—with real examples of families saved from self-destruction.', isPreview: false },
          { id: 'l6.5', title: 'The Phoenix Protocol: When Laws Change, Your Wealth Rebirths', duration: 50, youtubeVideoId: 'EW5YCJNyZ_Y', content: 'How to build escape hatches into your legacy plan that allow assets to automatically transfer to new jurisdictions and structures when laws change—making your wealth truly immortal.', isPreview: false },
        ],
      },
    ],
  },
  // Course 7
  {
    id: 'guy-fawkes-7',
    name: 'THE HARDCORE BUNDLE',
    shortDescription: 'COMPLETE SYSTEM DISSOLUTION BUNDLE: The 6-Step Path From Slave to Sovereign.',
    longDescription: "This isn't a course collection. It's your total liberation protocol. Six courses, 30 videos. One mission: Make you completely untouchable by any system, government, or predator. From vanishing your digital identity to building multi-generational wealth fortresses—this bundle contains the exact systems the ultra-wealthy use to stay free while you struggle. You'll learn to legally owe $0 in taxes, move millions across borders without permission, hide assets from every creditor on earth, and lock your legacy away forever. This is the complete operating system for human sovereignty. The system was designed to keep you small. This bundle is designed to make you unstoppable.",
    price: 222,
    vendettaMachineUrl: 'https://vendetta-machine.vercel.app/art/guy-fawkes-7',
    imageId: 'course-hardcore-bundle',
    teaserVideoUrl: 'https://youtu.be/ub9QhzU9GHs',
    category: 'Bundle',
    duration: '30 hours',
    level: 'Expert',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 137,
    introductionScript: "Welcome to the end of the line. You are here because you are done playing by their rules. This bundle is not just information; it is a weapon. A weapon against the systems of control that have been built around you since birth. We are going to dismantle them, one by one. Identity. Taxation. Banking. Legal liability. Mortality itself. We are going to rebuild your life on a foundation of absolute sovereignty. It will be hard. It will require you to unlearn everything you think you know about how the world works. But on the other side of this work lies the only thing that matters: true, unadulterated freedom. Let's get to work.",
    modules: [
      {
        id: 'm1',
        title: 'Complete Curriculum',
        lessons: [
          // From Course 1
          { id: 'l1.1', title: 'Your Name is a Target: Why You\'re Being Hunted Right Now', duration: 25, youtubeVideoId: 'Z_15Zv8js9I', content: 'The brutal truth about how your single identity makes you a sitting duck for data brokers, debt collectors, and government overreach—and why having one name is the ultimate vulnerability in 2025.', isPreview: true },
          { id: 'l1.2', title: 'Create Your First Fake Identity (Yes, It\'s Legal)', duration: 35, youtubeVideoId: 'Lu9mpBV0YjY', content: 'Step-by-step walkthrough of building your first operational alias—from generating a believable backstory to creating digital footprints that pass even deep background checks. No shady tactics, just smart legal loopholes.', isPreview: false },
          { id: 'l1.3', title: 'Delete Your Digital Shadow: The 5-Minute Purge', duration: 30, youtubeVideoId: 'astqlEQVW68', content: 'The exact tools and scripts to mass-delete your personal data from 90% of data broker sites in under 5 minutes. Watch your digital shadow shrink in real-time as you regain control.', isPreview: false },
          { id: 'l1.4', title: 'Trick KYC Systems: Give Them Fake Clues That Work', duration: 28, youtubeVideoId: '-Ftq8Xyuocw', content: 'How to satisfy bank and exchange verification requirements by strategically leaking false information that satisfies their algorithms while protecting your real identity. The art of controlled digital deception.', isPreview: false },
          { id: 'l1.5', title: 'Run 3 Identities Like a Spy: Your Digital Army', duration: 40, youtubeVideoId: 'rjyy0l2Z0Os', content: 'Advanced compartmentalization tactics for managing multiple personas simultaneously—each with its own email, phone number, and digital history—without cross-contamination or burnout.', isPreview: false },
          // From Course 2
          { id: 'l2.1', title: 'Your Birthplace is a Prison: Break Free NOW', duration: 30, youtubeVideoId: '5HoDzfZgxjQ', content: 'How your country of birth is the single biggest financial liability you have—and the exact legal pathways to sever its claim on your wealth without ever setting foot in another country.', isPreview: false },
          { id: 'l2.2', title: 'Buy Your Second Passport (Before They Close the Door)', duration: 45, youtubeVideoId: 'rXbAqAzAdjA', content: 'The last remaining citizenship-by-investment programs that still work in 2025, with exact ROI calculations showing how much you\'ll save versus the $100k-$2M investment required.', isPreview: false },
          { id: 'l2.3', title: 'Live Anywhere, Pay Taxes Nowhere: The Digital Nomad Lie EXPOSED', duration: 40, youtubeVideoId: 'k0TfNd4LJnE', content: 'Why "digital nomad visas" are tax traps for the naive—and the real strategy of using temporary residency to establish permanent tax freedom while maintaining your lifestyle.', isPreview: false },
          { id: 'l2.4', title: 'The \'Nowhere Man\' Trick: How to Disappear From Tax Records', duration: 35, youtubeVideoId: '0dBIDK9fhPY', content: 'Advanced jurisdictional layering techniques that make you legally stateless for tax purposes while maintaining full banking access and travel freedom—no physical relocation required.', isPreview: false },
          { id: 'l2.5', title: 'Your Government Hates You: Play Countries Against Each Other', duration: 50, youtubeVideoId: 'tDnw2_0LYJQ', content: 'How to create legal conflict between tax authorities so they waste years fighting each other while your money grows untouched in neutral jurisdictions.', isPreview: false },
          // From Course 3
          { id: 'l3.1', title: 'Own Nothing, Control Everything: The Billionaire Secret', duration: 35, youtubeVideoId: 'zRyv3w71QdM', content: 'The psychological shift from "ownership" to "control"—and how the world\'s wealthiest families legally separate themselves from their assets while maintaining absolute command.', isPreview: false },
          { id: 'l3.2', title: 'Wyoming LLCs: Your First Legal Force Field', duration: 45, youtubeVideoId: 'CSQUawo1jPs', content: 'Why Wyoming is the ultimate domestic asset protection haven—and the exact setup to create an LLC that laughs at lawsuits while maintaining full operational control from your living room.', isPreview: false },
          { id: 'l3.3', title: 'The Trust That Can\'t Be Broken (Even by Your Worst Enemy)', duration: 50, youtubeVideoId: 'mmoX6JJ7Cuc', content: 'How to structure an offshore asset protection trust with "Trust Protector" powers that let you fire trustees, veto distributions, and maintain de facto control while legally owning nothing.', isPreview: false },
          { id: 'l3.4', title: 'Stack Legal Shields: Make Lawsuits Give Up in 3 Days', duration: 40, youtubeVideoId: 'kUVvhE0a5yM', content: 'The multi-layered entity strategy that forces creditors to sue through 3-4 legal entities across different jurisdictions—making the cost of pursuit exceed any potential recovery.', isPreview: false },
          { id: 'l3.5', title: 'Pull the Strings From Shadows: Control Without Your Name', duration: 30, youtubeVideoId: 'Z9oIPP-hOKg', content: 'Advanced techniques for managing your entire empire through nominees, corporate directors, and private agreements—keeping your name completely absent from public records while retaining 100% control.', isPreview: false },
          // From Course 4
          { id: 'l4.1', title: 'Banks Are Spying On You: Here\'s Your Escape Plan', duration: 30, youtubeVideoId: 'mxbABgXM4is', content: 'The shocking truth about how banks monitor your spending habits, report "suspicious activity," and freeze accounts—and the exact timeline for migrating your entire financial life off their radar.', isPreview: false },
          { id: 'l4.2', title: 'Your Crypto is at Risk: The $0 Security Setup That Works', duration: 40, youtubeVideoId: 'RTl4sS_E1bQ', content: 'How to secure millions in cryptocurrency using free, open-source tools that make exchanges and hardware wallets look like child\'s play—with step-by-step setup guides.', isPreview: false },
          { id: 'l4.3', title: 'Create Your Private USD: Stablecoins That Can\'t Be Frozen', duration: 35, youtubeVideoId: 'Gmg3VRg15mE', content: 'Why USDT and USDC are dangerous—and how to use decentralized, over-collateralized stablecoins that maintain dollar value while being completely censorship-resistant.', isPreview: false },
          { id: 'l4.4', title: 'Move $1M Without a Trace: The Invisible Transfer Method', duration: 45, youtubeVideoId: 'SxKF7HCcroY', content: 'The multi-hop DEX routing strategy that breaks chain analysis and makes large transfers completely untraceable—tested against Chainalysis and Elliptic tools.', isPreview: false },
          { id: 'l4.5', title: 'Cash Out $100k Daily: Dark Web Methods (Made Legal)', duration: 50, youtubeVideoId: 'VppVZgdutPE', content: 'How to convert cryptocurrency to physical cash through legitimate peer-to-peer networks, local merchants, and cash-intensive businesses without triggering KYC red flags.', isPreview: false },
          // From Course 5
          { id: 'l5.1', title: 'Tax Evasion vs Tax Avoidance: The Gray Zone That Saves Millions', duration: 30, youtubeVideoId: 'QS23vRQ0Ab0', content: 'The exact legal line between what\'s prosecutable and what\'s perfectly legal—with real case studies of people who saved $2M+ by operating in the gray zone without crossing into criminal territory.', isPreview: false },
          { id: 'l5.2', title: 'Live in Paradise, Pay $0 Tax: The Territorial Tax Hack', duration: 45, youtubeVideoId: '9SzTuOrs6Xo', content: 'How to exploit territorial tax systems in Dubai, Puerto Rico, and Georgia to earn unlimited global income while legally paying zero taxes—and the exact residency requirements to make it stick.', isPreview: false },
          { id: 'l5.3', title: 'Shift $1M in Profits Overnight: The Corporate Shell Game', duration: 50, youtubeVideoId: '8sYVX-u90_U', content: 'The multi-entity profit shifting strategy used by Fortune 500 companies—adapted for individual entrepreneurs to legally move income to zero-tax jurisdictions while maintaining full operational control.', isPreview: false },
          { id: 'l5.4', title: 'Title Your Assets to Be \'Legally Invisible\' to Creditors', duration: 40, youtubeVideoId: 'lEe6ofBvC9w', content: 'Advanced asset titling protocols that make your real estate, vehicles, and investments completely disappear from public records and creditor searches while maintaining your use and control.', isPreview: false },
          { id: 'l5.5', title: 'When IRS Knocks: The 3-Word Response That Shuts Them Down', duration: 35, youtubeVideoId: 'PWaMBXAdQEU', content: 'The exact legal language and procedural tactics to delay, derail, and defeat tax audits—including template letters that force agents to close cases due to procedural violations.', isPreview: false },
          // From Course 6
          { id: 'l6.1', title: 'Your Will is a Suicide Note: Why Your Family Will Lose Everything', duration: 30, youtubeVideoId: 'fmN92puUIaM', content: 'The brutal truth about probate court—and how 78% of estates lose over 40% of their value to taxes, lawyers, and family fighting within 18 months of death.', isPreview: false },
          { id: 'l6.2', title: 'Build a Dynasty Trust: Your Wealth That Outlives You by 200 Years', duration: 45, youtubeVideoId: 'RN6LcKiHiE0', content: 'How to structure a perpetual trust that legally bypasses estate taxes, survives multiple generations, and maintains absolute control over how and when beneficiaries receive funds.', isPreview: false },
          { id: 'l6.3', title: 'Your Crypto Will Die With You: The Digital Inheritance Time Bomb', duration: 40, youtubeVideoId: '10ms1p-f-ws', content: 'The exact protocols to ensure your Bitcoin, Ethereum, and digital assets survive your death—including multi-sig inheritance setups and dead man\'s switches that activate automatically.', isPreview: false },
          { id: 'l6.4', title: 'Protect Stupid Kids: Give Them Money Without Letting Them Ruin It', duration: 35, youtubeVideoId: 'v9vqg54VjS0', content: 'Advanced trust provisions that provide heirs with comfortable lifestyles while restricting access to principal until they prove financial maturity—with real examples of families saved from self-destruction.', isPreview: false },
          { id: 'l6.5', title: 'The Phoenix Protocol: When Laws Change, Your Wealth Rebirths', duration: 50, youtubeVideoId: 'EW5YCJNyZ_Y', content: 'How to build escape hatches into your legacy plan that allow assets to automatically transfer to new jurisdictions and structures when laws change—making your wealth truly immortal.', isPreview: false },
        ],
      },
    ],
  },
  // Course 8
  {
    id: 'guy-fawkes-8',
    name: 'PRIVATE FINANCIAL CONSULTANT',
    shortDescription: 'CLONE OF MY FINANCIAL BRAIN. Stop guessing. Ask my AI clone.',
    longDescription: 'Consultants are expensive. Lawyers are snitches. And asking for advice on a public forum is financial suicide. You have specific, dangerous questions about your situation that you can\'t trust with a human. "How do I hide my specific assets?" "What if my ex finds out?" "Is this specific transfer flagged?" Enter The Black Box. We have force-fed every loophole, every legal structure, and every evasion tactic from this entire curriculum into a private, isolated AI neural net. It doesn\'t judge. It doesn\'t sleep. And most importantly, it doesn\'t keep logs. It is a clone of my financial brain, available 24/7 to architect your specific escape plan in seconds. Stop guessing. Start executing.',
    price: 123,
    vendettaMachineUrl: 'https://vendetta-machine.vercel.app/art/guy-fawkes-8',
    imageId: 'course-private-consultant',
    teaserVideoUrl: 'https://youtu.be/Qt6FOXdnQ3M',
    category: 'AI Tool',
    duration: 'Unlimited',
    level: 'Expert',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 152,
    thumbnailUrl: placeholderThumbnail,
    notebookLmUrl: 'https://notebooklm.google.com/notebook/1ed52c6c-bc0d-4a55-a1ec-bacac4220f8f',
    introductionScript: "I cannot be everywhere at once. But my knowledge can. This tool is the culmination of everything I know, distilled into a pure, queryable form. It is not a chat bot. It is a tactical advisor. Use it to stress-test your plans, to find the loopholes I haven't explicitly covered, and to build a strategy that is uniquely yours. Treat it with respect, and it will give you the keys to the kingdom.",
    modules: [
      {
        id: 'm1',
        title: 'Access The Financial Brain',
        lessons: [
          { id: 'l8.1', title: 'Neural Link Interface', duration: 10, youtubeVideoId: 'jNQXAC9IVRw', content: 'Direct interface with the Commander\'s AI clone. Ask specific questions, get specific strategies.', isPreview: true },
        ],
      },
    ],
  },
  // Course 9
  {
    id: 'guy-fawkes-9',
    name: 'SOFTCORE BUNDLE',
    shortDescription: 'The essential introduction to escaping the rat race and seeing the strings.',
    longDescription: "You feel it, don’t you? That gnawing sense that something is fundamentally wrong. You did everything right. You went to school. You got the job. You pay your taxes. And yet, you’re falling behind. Inflation eats your savings. Taxes eat your salary. The \"American Dream\" feels more like a hallucination. You aren’t crazy. You are being farmed. This bundle is your wake-up call. Before you can escape the prison, you have to see the bars. We strip away the comfortable lies of the financial system to show you the brutal machinery underneath. You will learn how money is actually created, why your savings account is a scam, and how the \"safe path\" is guaranteed to keep you poor forever. This isn’t about complex legal structures yet—it’s about deprogramming the slave mindset you were raised with. Take the Red Pill. See the truth.",
    price: 87,
    vendettaMachineUrl: 'https://vendetta-machine.vercel.app/art/guy-fawkes-9',
    imageId: 'course-softcore-bundle',
    teaserVideoUrl: 'https://youtu.be/i6BD7vpM_4k',
    category: 'Bundle',
    duration: '15 hours',
    level: 'Beginner',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 72,
    thumbnailUrl: placeholderThumbnail,
    introductionScript: "Welcome. If you are here, it means you have started to ask the right questions. Why does the system feel rigged? Why does working harder not make you richer? Why does it feel like you are running on a treadmill that is slowly speeding up? The answer is simple: because you are. In this collection, we are going to stop running. We are going to step off the machine and look at it. We are going to understand the mechanics of your enslavement so that you can begin to plan your escape. This is the beginning of your real education.",
    modules: [
      {
        id: 'm1',
        title: 'System Deconstruction',
        lessons: [
          { id: 'l9.1', title: 'The Myth of the Singular Self', duration: 30, youtubeVideoId: '9cwyUpYjiFk', content: 'A foundational lesson on why having one consistent identity across all aspects of your life makes you a predictable and vulnerable target for corporations and governments.', isPreview: true },
          { id: 'l9.2', title: 'Forging Your First Persona', duration: 30, youtubeVideoId: 'nPMsiKlAXqk', content: 'A practical, step-by-step guide to creating a separate, believable digital identity from scratch, complete with its own footprint and history.', isPreview: false },
          { id: 'l9.3', title: 'The Digital Ghost', duration: 30, youtubeVideoId: 'I0L9aVaKXxA', content: 'Master the tools and daily operational security (OPSEC) techniques required to erase your digital footprints and ensure your activities remain compartmentalized and private.', isPreview: false },
          { id: 'l9.4', title: 'The Verification Game', duration: 30, youtubeVideoId: 'qB9VpU7QgYs', content: 'Discover the art of controlled identity leakage—how to satisfy Know Your Customer (KYC) checks and other verification systems without revealing your true, core information.', isPreview: false },
          { id: 'l9.5', title: 'Building Your Persona Ecosystem', duration: 30, youtubeVideoId: '4chP-Q95whI', content: 'Learn the advanced strategy of managing multiple identities so they can work together to achieve your goals without ever intersecting or compromising one another.', isPreview: false },
          { id: 'l9.6', title: 'Escaping the Birthplace Lottery', duration: 30, youtubeVideoId: 'JdGbCqcygII', content: 'Understand the core concept of jurisdictional arbitrage and why your country of birth does not have to determine your financial future.', isPreview: false },
          { id: 'l9.7', title: 'The Modern Flag Theory Playbook', duration: 30, youtubeVideoId: 'vxwOGd5fgx0', content: 'A 21st-century update to the classic "Five Flags" theory, tailored for the digital age of remote work, e-residency, and cryptocurrency.', isPreview: false },
          { id: 'l9.8', title: 'The Passport Portfolio', duration: 30, youtubeVideoId: 'DWyhvXGTsEc', content: 'A strategic guide to Citizenship by Investment (CBI) programs—how to analyze, acquire, and use a second passport for global mobility and security.', isPreview: false },
          { id: 'l9.9', title: 'The Nomad\'s Gambit: Residency without Obligation', duration: 30, youtubeVideoId: 'riDk-ZjJztg', content: 'Learn to leverage Digital Nomad visas and non-domicile tax regimes to establish legal presence without becoming a full tax resident.', isPreview: false },
          { id: 'l9.10', title: 'The Nowhere Man Protocol', duration: 30, youtubeVideoId: 'tvnf-NKKz7Y', content: 'The ultimate strategy: Learn how to layer citizenships, residencies, and entities to create deliberate jurisdictional ambiguity, making you the hardest possible target.', isPreview: false },
          { id: 'l9.11', title: 'The Core Principle of Control Without Ownership', duration: 30, youtubeVideoId: 'J469RL4AjR8', content: 'A paradigm-shifting lesson on why legal ownership makes you a target and how the world\'s wealthiest use structures to maintain absolute control without it.', isPreview: false },
          { id: 'l9.12', title: 'Choosing Your Holding Company: Building Your Fortress', duration: 30, youtubeVideoId: 'R_Dn9EPc6is', content: 'A deep dive into the strategic advantages of jurisdictions like Wyoming and Nevis, guiding you on where to build the foundation of your entire corporate structure.', isPreview: false },
          { id: 'l9.13', title: 'The Unbreakable Shield: Asset Protection Trusts', duration: 30, youtubeVideoId: 'gjNddJkDShA', content: 'An essential guide to the most powerful asset protection tool known to man—the offshore trust—and how to structure it to be legally impenetrable.', isPreview: false },
          { id: 'l9.14', title: 'Layering Your Defense: The Entity Stack', duration: 30, youtubeVideoId: 'fk9Qr5noMDk', content: 'Learn the advanced technique of stacking LLCs under holding companies and placing them within trusts, creating a multi-layered defense that is a nightmare to attack.', isPreview: false },
          { id: 'l9.15', title: 'The Trust Protector', duration: 30, youtubeVideoId: 'TkRc421HsS0', content: 'Discover the secret weapon of modern trusts—the Protector—and how you can use this role to retain ultimate authority over your assets without being the legal owner or trustee.', isPreview: false },
          { id: 'l9.16', title: 'Crypto as Sovereign Infrastructure', duration: 30, youtubeVideoId: 'JomWg10F1zQ', content: 'A foundational lesson reframing cryptocurrency not as a speculative asset, but as an essential, private, and censorship-resistant infrastructure for your wealth.', isPreview: false },
          { id: 'l9.17', title: 'Mastering Self-Custody: Your Keys, Your Kingdom', duration: 30, youtubeVideoId: 'IPc0QT72k5g', content: 'A practical, step-by-step guide to securing your digital assets. Learn the difference between hot and cold storage and how to never again trust an exchange with your money.', isPreview: false },
          { id: 'l9.18', title: 'Building a Private Global Bank: The Stablecoin Stack', duration: 30, youtubeVideoId: 'gsb0nIoXevQ', content: 'Discover how to use stablecoins as your primary medium of exchange, creating a diversified, blockchain-based dollar account that is outside the traditional banking system.', isPreview: false },
          { id: 'l9.19', title: 'The Art of the Invisible Transfer', duration: 30, youtubeVideoId: 'OjxPoeFa9Xs', content: 'Learn the operational security (OPSEC) needed to transact privately. Master decentralized exchanges (DEXs) and mixing protocols to break the chain of analysis.', isPreview: false },
          { id: 'l9.20', title: 'Financial Sovereignty', duration: 30, youtubeVideoId: '5WnG016xhWc', content: 'The most critical skill: a strategic guide to the various ways you can convert crypto to cash and vice-versa, with a focus on peer-to-peer and low-KYC methods.', isPreview: false },
          { id: 'l9.21', title: 'The Tax Spectrum: From Avoidance to Evasion', duration: 30, youtubeVideoId: 'QS23vRQ0Ab0', content: 'A critical lesson on understanding the legal "gray zone." Learn where the line is between smart, legal tax minimization and illegal evasion, and how to operate confidently.', isPreview: false },
          { id: 'l9.22', title: 'The Profit Shifting Machine', duration: 30, youtubeVideoId: 'n_kmySI1hr4', content: 'Learn how multinational corporations play the game. A practical guide to using multiple entities to source revenue, allocate expenses, and book profits in the most tax-efficient way possible.', isPreview: false },
          { id: 'l9.23', title: 'The Untouchable Title: Building Your Invisible Armor', duration: 30, youtubeVideoId: 'Rk0K4towuUc', content: 'Master the advanced art of asset titling. Learn how the precise way you hold title to real estate, businesses, and portfolios can make them legally unreachable in a lawsuit.', isPreview: false },
          { id: 'l9.24', title: 'The Territorial Tax Gambit: Audit Defense Protocol', duration: 30, youtubeVideoId: 'POQXaIqgeoE', content: 'Scrutiny is inevitable. This lesson provides a step-by-step playbook for how to prepare for and respond to a tax audit or legal inquiry without incriminating yourself or compromising your structure.', isPreview: false },
          { id: 'l9.25', title: 'Control Without Ownership: The Territorial Tax Gambit', duration: 30, youtubeVideoId: 'kkNTL7tzL8E', content: 'An in-depth guide to the world\'s most favorable tax systems. Discover how to legally earn income from anywhere in the world while being a tax resident of a jurisdiction that won\'t tax it.', isPreview: false },
          { id: 'l9.26', title: 'The Will is a Trap: Why Traditional Estate Planning Fails', duration: 30, youtubeVideoId: 'GtSoP837cFA', content: 'A critical look at the probate system and why a last will and testament is one of the least effective ways to transfer wealth privately and efficiently.', isPreview: false },
          { id: 'l9.27', title: 'The Dynasty Trust: Your Family\'s Operating System', duration: 30, youtubeVideoId: 'jBzbnJGMSNo', content: 'A complete guide to structuring a dynasty trust—a powerful legal entity designed to hold and manage assets for multiple generations while protecting them from taxes and creditors.', isPreview: false },
          { id: 'l9.28', title: 'The Digital Afterlife: Passing on Your Crypto & Online Assets', duration: 30, youtubeVideoId: 'ZNNqxTsXpPg', content: 'A vital protocol for the 21st century. Learn the specific, secure steps required to ensure your digital keys, crypto wallets, and online accounts are transferred safely to your heirs.', isPreview: false },
          { id: 'l9.29', title: 'The Wise Ancestor: Protecting Heirs from Themselves', duration: 30, youtubeVideoId: '_Lw3CwWkJBM', content: 'Discover how to write trust provisions that act as a guiding hand from the past, incentivizing productive behavior and protecting beneficiaries from squandering their inheritance.', isPreview: false },
          { id: 'l9.30', title: 'Building Your Fortress: Future-Proofing Your Legacy', duration: 30, youtubeVideoId: 'FY2E7Sc4eMQ', content: 'An advanced strategy on building adaptation into your legacy plan, allowing it to evolve and even transfer its assets into new structures to survive unforeseen changes in laws and geopolitics.', isPreview: false },
        ],
      },
    ],
  },
];

export const getCourseById = (id: string): Course | undefined => {
  return courses.find((course) => course.id === id);
};
