import { Course, Instructor } from './types';

export const instructors: Instructor[] = [
  {
    id: 'instructor-1',
    name: 'John Doe',
    avatarId: 'instructor-avatar-1',
    bio: 'Expert in financial markets with over 15 years of experience in stock trading and investment strategies. Proven track record of mentoring successful traders.',
  },
  {
    id: 'instructor-2',
    name: 'Jane Smith',
    avatarId: 'instructor-avatar-2',
    bio: 'A leading voice in the cryptocurrency space, Jane specializes in blockchain technology and decentralized finance. She is passionate about making crypto accessible to everyone.',
  },
];

export const courses: Course[] = [
  {
    id: 'course-1',
    name: 'The Sovereign Self: The Architecture of Anonymity',
    shortDescription: 'Learn the art of strategic invisibility and forge a collection of masks to move through the digital and financial world unseen.',
    longDescription: 'You have a name, a number, a digital shadow that follows you everywhere. You believe it\'s you, but it\'s not. It’s a target. This is not a course; it is an unlearning. Here, you will learn the art of strategic invisibility. We will teach you to shatter the single identity that makes you vulnerable and forge a collection of masks, each with a purpose. You will become a ghost in the machine—an operator who can move through the digital and financial world unseen, untracked, and in complete control. This is the foundation of all true freedom. Before you can protect your assets, you must first master yourself.',
    price: 199.99,
    imageId: 'course-sovereign-self',
    teaserVideoUrl: '/videos/sovereign-self-teaser.mp4',
    category: 'Security',
    duration: '4 hours',
    level: 'Advanced',
    instructor: instructors[0],
    rating: 4.9,
    studentsCount: 1024,
    introductionScript: "Hello. Welcome. Before we talk about money, or entities, or anything else, we need to talk about you. Or rather, the 'you' the world thinks it knows. You have a digital footprint, a legal name, a data trail that defines and confines you. But what if that was a choice, not a fact? In this course, I'm not going to teach you how to hide. I'm going to show you how to be everywhere and nowhere at once. We will deconstruct the idea of a single self and rebuild it as a powerful, multi-faceted tool. You will learn to create personas, control your data, and navigate the systems of verification not as a subject, but as a master. This is the first and most important step. Let's begin.",
    modules: [
      {
        id: 'm1',
        title: 'Foundations of Anonymity',
        lessons: [
          { id: 'l1.1', title: 'The Myth of the Singular Self', duration: 25, youtubeVideoId: 'jNQXAC9IVRw', content: 'A foundational lesson on why having one, consistent identity across all aspects of your life makes you a predictable and vulnerable target for corporations and governments.', isPreview: true },
          { id: 'l1.2', title: 'Forging Your First Persona', duration: 35, youtubeVideoId: 'jNQXAC9IVRw', content: 'A practical, step-by-step guide to creating a separate, believable digital identity from scratch, complete with its own footprint and history.', isPreview: false },
          { id: 'l1.3', title: 'The Art of the Digital Ghost', duration: 30, youtubeVideoId: 'jNQXAC9IVRw', content: 'Master the tools and daily operational security (OPSEC) techniques required to erase your digital footprints and ensure your activities remain compartmentalized and private.', isPreview: false },
          { id: 'l1.4', title: 'The Verification Game', duration: 28, youtubeVideoId: 'jNQXAC9IVRw', content: 'Discover the art of controlled identity leakage—how to satisfy Know Your Customer (KYC) checks and other verification systems without revealing your true, core information.', isPreview: false },
          { id: 'l1.5', title: 'Building Your Persona Ecosystem', duration: 40, youtubeVideoId: 'jNQXAC9IVRw', content: 'Learn the advanced strategy of managing multiple identities so they can work together to achieve your goals without ever intersecting or compromising one another.', isPreview: false },
        ],
      },
    ],
  },
  {
    id: 'course-2',
    name: 'Jurisdictional Arbitrage: The World is Your Weapon',
    shortDescription: 'See the globe as a chessboard, where citizenships, residencies, and legal systems are pieces you can move to your advantage.',
    longDescription: 'You were born in one place, but you don\'t have to live in its cage. The map of the world, with its rigid borders and tax laws, is an illusion for those who don\'t know the rules of the game. This course is the playbook. We will teach you to see the globe as a chessboard, where citizenships, residencies, and legal systems are pieces you can move to your advantage. Learn to legally escape the "birthplace lottery," play jurisdictions against each other, and plant flags where you are treated best. Stop being a citizen of a country and start becoming a citizen of the world, bound by no single power.',
    price: 249.99,
    imageId: 'course-jurisdictional-arbitrage',
    teaserVideoUrl: '/videos/jurisdictional-arbitrage-teaser.mp4',
    category: 'Global Strategy',
    duration: '5 hours',
    level: 'Expert',
    instructor: instructors[0],
    rating: 4.9,
    studentsCount: 850,
    introductionScript: "You were taught that the map of the world is fixed. That the country you were born in holds permanent power over your wealth and your freedom. I am here to tell you that this is a lie, a story told to keep you in place. In this course, we are going to redraw that map. I will show you how to turn borders into opportunities and passports into keys. You will learn the strategies to acquire new residencies and citizenships, how to structure your life to legally owe nothing to the countries that seek to tax you most, and how to become a 'Nowhere Man'—present where you need to be, but legally anchored nowhere. Your geography is no longer your destiny. It's your greatest weapon.",
    modules: [
      {
        id: 'm1',
        title: 'Global Citizenship Strategy',
        lessons: [
          { id: 'l2.1', title: 'Escaping the Birthplace Lottery', duration: 30, youtubeVideoId: 'jNQXAC9IVRw', content: 'Understand the core concept of jurisdictional arbitrage and why your country of birth does not have to determine your financial future.', isPreview: true },
          { id: 'l2.2', title: 'The Modern Flag Theory Playbook', duration: 45, youtubeVideoId: 'jNQXAC9IVRw', content: 'A 21st-century update to the classic "Five Flags" theory, tailored for the digital age of remote work, e-residency, and cryptocurrency.', isPreview: false },
          { id: 'l2.3', title: 'The Passport Portfolio', duration: 40, youtubeVideoId: 'jNQXAC9IVRw', content: 'A strategic guide to Citizenship by Investment (CBI) programs—how to analyze, acquire, and use a second passport for global mobility and security.', isPreview: false },
          { id: 'l2.4', title: 'The Nomad\'s Gambit: Residency without Obligation', duration: 35, youtubeVideoId: 'jNQXAC9IVRw', content: 'Learn to leverage Digital Nomad visas and non-domicile tax regimes to establish legal presence without becoming a full tax resident.', isPreview: false },
          { id: 'l2.5', title: 'The "Nowhere Man" Protocol', duration: 50, youtubeVideoId: 'jNQXAC9IVRw', content: 'The ultimate strategy: Learn how to layer citizenships, residencies, and entities to create deliberate jurisdictional ambiguity, making you the hardest possible target.', isPreview: false },
        ],
      },
    ],
  },
  {
    id: 'course-3',
    name: 'The Architect\'s Toolkit: Corporate Veils & Trust Fortresses',
    shortDescription: 'Build a fortress of legal entities and trusts so formidable it becomes invisible, placing your work beyond the reach of any enemy.',
    longDescription: 'Your wealth is exposed. Without the right structure, it is a single lawsuit, a jealous government, or a bitter dispute away from being lost forever. This course is your architectural blueprint to financial immortality. Learn to build a fortress of legal entities and trusts so formidable it becomes invisible. We will teach you how to use corporate veils not just as shields, but as weapons. You will master the art of controlling everything while legally owning nothing, placing your life\'s work beyond the reach of any enemy. Stop just *having* assets; start *architecting* their absolute protection.',
    price: 299.99,
    imageId: 'course-architect-toolkit',
    teaserVideoUrl: '/videos/architect-toolkit-teaser.mp4',
    category: 'Asset Protection',
    duration: '6 hours',
    level: 'Expert',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 1230,
    introductionScript: "Look at any great fortune, and you will not find a person. You will find a structure. A web of companies, a fortress of trusts. The wealthy learned long ago that ownership is a liability. Control is what matters. In this course, I will hand you the same tools. You'll learn to think not like an investor, but like an architect. We'll build your financial fortress brick by brick, from the Wyoming LLC that forms the foundation to the Cook Islands Trust that serves as the impregnable keep. I'll show you how to layer these entities, how to manage them remotely, and how to use them to create a perfect separation between you and your wealth. This is where your assets become truly untouchable.",
    modules: [
      {
        id: 'm1',
        title: 'Building Your Financial Fortress',
        lessons: [
          { id: 'l3.1', title: 'Control, Don\'t Own: The Core Principle of Protection', duration: 35, youtubeVideoId: 'jNQXAC9IVRw', content: 'A paradigm-shifting lesson on why legal ownership makes you a target and how the world\'s wealthiest use structures to maintain absolute control without it.', isPreview: true },
          { id: 'l3.2', title: 'The Bedrock: Choosing Your Holding Company', duration: 45, youtubeVideoId: 'jNQXAC9IVRw', content: 'A deep dive into the strategic advantages of jurisdictions like Wyoming and Nevis, guiding you on where to build the foundation of your entire corporate structure.', isPreview: false },
          { id: 'l3.3', title: 'The Unbreakable Shield: The Asset Protection Trust', duration: 50, youtubeVideoId: 'jNQXAC9IVRw', content: 'An essential guide to the most powerful asset protection tool known to man—the offshore trust—and how to structure it to be legally impenetrable.', isPreview: false },
          { id: 'l3.4', title: 'Layering Your Defenses: The Entity Stack', duration: 40, youtubeVideoId: 'jNQXAC9IVRw', content: 'Learn the advanced technique of stacking LLCs under holding companies and placing them within trusts, creating a multi-layered defense that is a nightmare to attack.', isPreview: false },
          { id: 'l3.5', title: 'The Hand on the Tiller: The Role of the Protector', duration: 30, youtubeVideoId: 'jNQXAC9IVRw', content: 'Discover the secret weapon of modern trusts—the Protector—and how you can use this role to retain ultimate authority over your assets without being the legal owner or trustee.', isPreview: false },
        ],
      },
    ],
  },
  {
    id: 'course-4',
    name: 'The Shadow Economy: Parallel Financial Systems',
    shortDescription: 'Build your own sovereign financial stack using crypto as unstoppable, permissionless money.',
    longDescription: 'The banking system is a cage. Every transaction is monitored, every wire is logged, and your access can be revoked at any time. It\'s time to build your own system. This course is your entry point into the parallel financial world of crypto. This isn\'t about buying the next moonshot coin; it\'s about using crypto as it was intended: as unstoppable, permissionless money. Learn to build your own sovereign financial stack, move value across the globe instantly and privately, and connect it back to the physical world on your own terms. Exit the system of surveillance and enter the world of true financial freedom.',
    price: 249.99,
    imageId: 'course-shadow-economy',
    teaserVideoUrl: '/videos/shadow-economy-teaser.mp4',
    category: 'Crypto',
    duration: '5 hours',
    level: 'Intermediate',
    instructor: instructors[1],
    rating: 4.8,
    studentsCount: 945,
    introductionScript: "You've heard about crypto. You've seen the hype, the speculation. Now, I want you to forget all of it. In this course, we're going to explore what cryptocurrency *really* is: an entirely new set of financial rails for the world. Rails that you can own. I'm going to teach you how to use this technology not as a gambler, but as a sovereign individual. You'll learn to build a private, stable financial base using stablecoins, transact anonymously using decentralized exchanges, and most importantly, how to create your own on-ramps and off-ramps to the real world, all without asking for permission. This is your personal central bank. Let's open the doors.",
    modules: [
      {
        id: 'm1',
        title: 'Crypto for Sovereignty',
        lessons: [
          { id: 'l4.1', title: 'Beyond Speculation: Crypto as Sovereign Infrastructure', duration: 30, youtubeVideoId: 'jNQXAC9IVRw', content: 'A foundational lesson reframing cryptocurrency—not as a speculative asset, but as an essential, private, and censorship-resistant infrastructure for your wealth.', isPreview: true },
          { id: 'l4.2', title: 'The Sovereign\'s Vault: Mastering Self-Custody', duration: 40, youtubeVideoId: 'jNQXAC9IVRw', content: 'A practical, step-by-step guide to securing your digital assets. Learn the difference between hot and cold storage and how to never again trust an exchange with your money.', isPreview: false },
          { id: 'l4.3', title: 'The Stablecoin Stack: Your Private Global Bank', duration: 35, youtubeVideoId: 'jNQXAC9IVRw', content: 'Discover how to use stablecoins as your primary medium of exchange, creating a diversified, blockchain-based dollar account that is outside the traditional banking system.', isPreview: false },
          { id: 'l4.4', title: 'The Art of the Invisible Transfer', duration: 45, youtubeVideoId: 'jNQXAC9IVRw', content: 'Learn the operational security (OPSEC) needed to transact privately. Master decentralized exchanges (DEXs) and mixing protocols to break the chain of analysis.', isPreview: false },
          { id: 'l4.5', title: 'The Bridge to Reality: On-Ramps & Off-Ramps', duration: 50, youtubeVideoId: 'jNQXAC9IVRw', content: 'The most critical skill: a strategic guide to the various ways you can convert crypto to cash and vice-versa, with a focus on peer-to-peer and low-KYC methods.', isPreview: false },
        ],
      },
    ],
  },
  {
    id: 'course-5',
    name: 'The Invisible Armor: Advanced Asset Protection & Tax Nullification',
    shortDescription: 'Transform your financial structure from a passive vault into a dynamic, invisible armor and reduce your tax burden to near zero.',
    longDescription: 'Taxes are not a certainty; they are a negotiation you are losing by default. Lawsuits are not random; they are attacks on the unprepared. This is the masterclass in active defense. Here, you will learn to transform your financial structure from a passive vault into a dynamic, invisible armor. We will teach you the strategies to legally route income, shift profits, and establish residencies that can reduce your tax burden to near zero. You will learn to title assets in a way that makes them untouchable. This is not about finding loopholes; it\'s about re-architecting your reality so the rules no longer apply.',
    price: 349.99,
    imageId: 'course-invisible-armor',
    teaserVideoUrl: '/videos/invisible-armor-teaser.mp4',
    category: 'Tax Strategy',
    duration: '7 hours',
    level: 'Expert',
    instructor: instructors[0],
    rating: 5.0,
    studentsCount: 780,
    introductionScript: "You have been taught to work hard, earn money, and then hand over a significant portion of it to a government that sees you as a resource. I'm here to offer you a different path. A path where tax is a choice, not a command. In this course, we move into the art of the active defense. I'll show you how corporate structures aren't just for protection, but for legally steering your profits to where they are treated best. We'll explore the world of territorial tax and non-domicile residency—the keys to unlocking a zero-tax life. This isn't evasion. This is superior design. You will learn to build a system so efficient and so robust that it simply becomes invisible to those who would seek to claim a piece of it.",
    modules: [
      {
        id: 'm1',
        title: 'Active Financial Defense',
        lessons: [
          { id: 'l5.1', title: 'The Tax Spectrum: From Avoidance to Evasion', duration: 30, youtubeVideoId: 'jNQXAC9IVRw', content: 'A critical lesson on understanding the legal "gray zone." Learn where the line is between smart, legal tax minimization and illegal evasion, and how to operate confidently.', isPreview: true },
          { id: 'l5.2', title: 'The Territorial Tax Gambit', duration: 45, youtubeVideoId: 'jNQXAC9IVRw', content: 'An in-depth guide to the world\'s most favorable tax systems. Discover how to legally earn income from anywhere in the world while being a tax resident of a jurisdiction that won\'t tax it.', isPreview: false },
          { id: 'l5.3', title: 'The Profit-Shifting Machine', duration: 50, youtubeVideoId: 'jNQXAC9IVRw', content: 'Learn how multinational corporations play the game. A practical guide to using multiple entities to source revenue, allocate expenses, and book profits in the most tax-efficient way possible.', isPreview: false },
          { id: 'l5.4', title: 'The Untouchable Title', duration: 40, youtubeVideoId: 'jNQXAC9IVRw', content: 'Master the advanced art of asset titling. Learn how the precise way you hold title to real estate, businesses, and portfolios can make them legally untouchable in a lawsuit.', isPreview: false },
          { id: 'l5.5', title: 'The Audit Defense Protocol', duration: 35, youtubeVideoId: 'jNQXAC9IVRw', content: 'Scrutiny is inevitable. This lesson provides a step-by-step playbook for how to prepare for and respond to a tax audit or legal inquiry without incriminating yourself or compromising your structure.', isPreview: false },
        ],
      },
    ],
  },
  {
    id: 'course-6',
    name: 'The Immortal Game: Legacy, Inheritance & the Multi-Generational Plan',
    shortDescription: 'Build a legacy architecture that bypasses the probate system and preserves your assets for generations.',
    longDescription: 'What is the point of building a fortress if its gates are thrown open the moment you are gone? A last will and testament is not a plan; it is a public invitation for governments and predators to feast on your life\'s work. This course is about achieving true immortality—for your wealth, your vision, and your family\'s future. Learn to build a legacy architecture using dynasty trusts and automated protocols that bypasses the entire probate system, protects your heirs from themselves, and preserves your assets for generations. Stop planning for your death; start designing your dynasty.',
    price: 399.99,
    imageId: 'course-immortal-game',
    teaserVideoUrl: '/videos/immortal-game-teaser.mp4',
    category: 'Legacy Planning',
    duration: '6 hours',
    level: 'Advanced',
    instructor: instructors[0],
    rating: 4.9,
    studentsCount: 650,
    introductionScript: "Everything you've built, everything you've learned—it can all be undone by one poorly written document: a will. The system is designed to take its cut the moment you're gone. But what if you could opt out? In this final course, we will build your masterpiece. Not a plan for your death, but an engine for your legacy. I will show you how to use perpetual trusts to create a structure that can last for centuries, guiding and providing for your family long after you're gone. We'll design protocols for the seamless transfer of all your assets, both physical and digital, completely outside of any government's view. This is the final move on the chessboard. This is how you win the game, forever.",
    modules: [
      {
        id: 'm1',
        title: 'Designing Your Dynasty',
        lessons: [
          { id: 'l6.1', title: 'The Will is a Trap: Why Traditional Estate Planning Fails', duration: 30, youtubeVideoId: 'jNQXAC9IVRw', content: 'A critical look at the probate system and why a last will and testament is one of the least effective ways to transfer wealth privately and efficiently.', isPreview: true },
          { id: 'l6.2', title: 'The Dynasty Trust: Your Family\'s Operating System', duration: 45, youtubeVideoId: 'jNQXAC9IVRw', content: 'A complete guide to structuring a dynasty trust—a powerful legal entity designed to hold and manage assets for multiple generations while protecting them from taxes and creditors.', isPreview: false },
          { id: 'l6.3', title: 'The Digital Afterlife: Passing on Your Crypto & Online Assets', duration: 40, youtubeVideoId: 'jNQXAC9IVRw', content: 'A vital protocol for the 21st century. Learn the specific, secure steps required to ensure your digital keys, crypto wallets, and online accounts are transferred safely to your heirs.', isPreview: false },
          { id: 'l6.4', title: 'The Wise Ancestor: Protecting Heirs from Themselves', duration: 35, youtubeVideoId: 'jNQXAC9IVRw', content: 'Discover how to write trust provisions that act as a guiding hand from the past, incentivizing productive behavior and protecting beneficiaries from squandering their inheritance.', isPreview: false },
          { id: 'l6.5', title: 'The Phoenix Protocol: Future-Proofing Your Legacy', duration: 50, youtubeVideoId: 'jNQXAC9IVRw', content: 'An advanced strategy on building adaptation into your legacy plan, allowing it to evolve and even transfer its assets into new structures to survive unforeseen changes in laws and geopolitics.', isPreview: false },
        ],
      },
    ],
  },
];

export const getCourseById = (id: string): Course | undefined => {
  return courses.find((course) => course.id === id);
};
